# Generated by Django 4.0.6 on 2022-12-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-orderDate', 'isApprove']},
        ),
    ]
